//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTEmployee()
        {
            this.TSTShopNotes = new HashSet<TSTShopNote>();
            this.TSTOrders = new HashSet<TSTOrder>();
            this.TSTOrders1 = new HashSet<TSTOrder>();
        }
    
        public int EmployeeID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public int DeptID { get; set; }
        public int EmpStatusID { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<System.DateTime> SeparationDate { get; set; }
        public decimal Salary { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string EmpPhoto { get; set; }
        public string JobTitle { get; set; }
        public string UserID { get; set; }
    
        public virtual TSTDepartment TSTDepartment { get; set; }
        public virtual TSTEmployeeStatus TSTEmployeeStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTShopNote> TSTShopNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTOrder> TSTOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTOrder> TSTOrders1 { get; set; }
    }
}
